sudo: required
servies:
  - docker

before_install:
  - docker build -t stevensuh/learning-docker -f Dockerfile.dev .

script:
  - docker run stevensuh/learning-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learning-docker"
  env: "LearningDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-520307415196"
  bucket_path: "learning-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
